import { createElement } from 'lwc';
import SfdxVisQualityGatesView from 'c/sfdxVisQualityGatesView';

describe('c-sfdx-vis-quality-gates-view', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-sfdx-vis-quality-gates-view', {
            is: SfdxVisQualityGatesView
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});