name: SonarCloud Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # Allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ✅ Step 2: Debug - List project files (to verify correct paths)
      - name: List Directory Structure
        run: ls -R

      # ✅ Step 3: SonarCloud Analysis
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Ensure this secret is added in GitHub
        with:
          args: >
            -Dsonar.projectKey=SONYSIMRAN_test-dx-visualizer
            -Dsonar.organization=sonysimran
            -Dsonar.sources=force-app/main/default
            -Dsonar.verbose=true
